### ISSUE TITLE
Compiling with Android NDK

### ISSUE THREAD

**Issue by archimedeschess** [Ciekce/Polaris#58]
When compiling with Android NDK (Clang) I get the following error message:
```
uci.cpp:828:18: fatal error: static_assert expression is not an integral constant expression
static_assert(NormalizationK == static_cast<i32>(std::reduce(As.begin(), As.end())));
```

**Comment by Ciekce** [comment]
`std::reduce` is only constexpr as of C++20, your compiler or stdlib seems to be outdated. As a workaround, you can simply comment out or delete that line (it only exists as a sanity check) - although you might run into other issues with C++20 features.

If you'd rather keep the sanity check around, you can replace that line with the following:
```c++
static_assert(NormalizationK == static_cast<i32>(As[0] + As[1] + As[2] + As[3]));
```

Hope this helps :)
